import type { MigrationInterface, QueryRunner } from "typeorm";

export class CreateGoodsReceiptAttachments1788090000000
  implements MigrationInterface
{
  async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`
      CREATE TABLE phieu_nhap_kho_chung_tu (
        id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        phieu_nhap_id integer NOT NULL,
        ten_goc varchar(255) NOT NULL,
        ten_luu varchar(100) NOT NULL UNIQUE,
        loai_tep varchar(150) NOT NULL,
        kich_thuoc integer NOT NULL,
        created_at timestamptz NOT NULL DEFAULT now(),
        CONSTRAINT fk_phieu_nhap_chung_tu
          FOREIGN KEY (phieu_nhap_id) REFERENCES phieu_nhap_kho(id)
          ON DELETE CASCADE
      )
    `);
    await queryRunner.query(`
      CREATE INDEX idx_phieu_nhap_chung_tu_phieu
      ON phieu_nhap_kho_chung_tu(phieu_nhap_id)
    `);
  }

  async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`DROP TABLE phieu_nhap_kho_chung_tu`);
  }
}
