import type { MigrationInterface, QueryRunner } from "typeorm";

export class ExpandGoodsIssue1788130000000 implements MigrationInterface {
  async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`ALTER TABLE phieu_xuat_kho
      ADD COLUMN dia_chi_bo_phan varchar(255), ADD COLUMN tai_khoan_no varchar(50), ADD COLUMN tai_khoan_co varchar(50),
      ADD COLUMN kho_xuat varchar(255), ADD COLUMN dia_diem varchar(255), ADD COLUMN tong_tien_bang_chu varchar(500),
      ADD COLUMN chung_tu_kem_the varchar(255), ADD COLUMN nguoi_lap_id integer REFERENCES users(id) ON DELETE SET NULL,
      ADD COLUMN thu_kho_id integer REFERENCES users(id) ON DELETE SET NULL, ADD COLUMN ke_toan_truong_id integer REFERENCES users(id) ON DELETE SET NULL`);
    await queryRunner.query(
      `ALTER TABLE phieu_xuat_kho_chi_tiet ADD COLUMN so_luong_chung_tu numeric(18,3)`,
    );
    await queryRunner.query(
      `UPDATE phieu_xuat_kho_chi_tiet SET so_luong_chung_tu = so_luong_xuat`,
    );
    await queryRunner.query(
      `ALTER TABLE phieu_xuat_kho_chi_tiet ALTER COLUMN so_luong_chung_tu SET NOT NULL, ADD CONSTRAINT chk_so_luong_chung_tu_xuat CHECK (so_luong_chung_tu >= 0)`,
    );
    await queryRunner.query(
      `CREATE TABLE phieu_xuat_kho_chung_tu (id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, phieu_xuat_id integer NOT NULL REFERENCES phieu_xuat_kho(id) ON DELETE CASCADE, ten_goc varchar(255) NOT NULL, ten_luu varchar(100) NOT NULL UNIQUE, loai_tep varchar(150) NOT NULL, kich_thuoc integer NOT NULL CHECK (kich_thuoc > 0), created_at timestamptz NOT NULL DEFAULT now())`,
    );
  }
  async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`DROP TABLE phieu_xuat_kho_chung_tu`);
    await queryRunner.query(
      `ALTER TABLE phieu_xuat_kho_chi_tiet DROP COLUMN so_luong_chung_tu`,
    );
    await queryRunner.query(
      `ALTER TABLE phieu_xuat_kho DROP COLUMN ke_toan_truong_id, DROP COLUMN thu_kho_id, DROP COLUMN nguoi_lap_id, DROP COLUMN chung_tu_kem_the, DROP COLUMN tong_tien_bang_chu, DROP COLUMN dia_diem, DROP COLUMN kho_xuat, DROP COLUMN tai_khoan_co, DROP COLUMN tai_khoan_no, DROP COLUMN dia_chi_bo_phan`,
    );
  }
}
