import type { MigrationInterface, QueryRunner } from "typeorm";

export class CreateOrganizationDepartment1788120000000 implements MigrationInterface {
  async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(
      `CREATE TABLE don_vi (id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, ma varchar(50) NOT NULL UNIQUE, ten varchar(255) NOT NULL UNIQUE, hoat_dong boolean NOT NULL DEFAULT true)`,
    );
    await queryRunner.query(
      `CREATE TABLE bo_phan (id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, don_vi_id integer NOT NULL REFERENCES don_vi(id) ON DELETE RESTRICT, ma varchar(50) NOT NULL UNIQUE, ten varchar(255) NOT NULL, hoat_dong boolean NOT NULL DEFAULT true)`,
    );
    await queryRunner.query(
      `INSERT INTO don_vi(ma, ten) SELECT 'DV_' || substr(md5(trim(don_vi)), 1, 8), trim(don_vi) FROM phieu_nhap_kho WHERE nullif(trim(don_vi), '') IS NOT NULL ON CONFLICT DO NOTHING`,
    );
    await queryRunner.query(
      `INSERT INTO don_vi(ma, ten) SELECT 'DV_MAC_DINH', 'Đơn vị mặc định' WHERE NOT EXISTS (SELECT 1 FROM don_vi)`,
    );
    await queryRunner.query(
      `INSERT INTO bo_phan(don_vi_id, ma, ten) SELECT DISTINCT organization.id, 'BP_' || substr(md5(trim(receipt.bo_phan) || organization.id::text), 1, 8), trim(receipt.bo_phan) FROM phieu_nhap_kho receipt JOIN don_vi organization ON organization.ten = trim(receipt.don_vi) WHERE nullif(trim(receipt.bo_phan), '') IS NOT NULL ON CONFLICT DO NOTHING`,
    );
    await queryRunner.query(
      `ALTER TABLE phieu_nhap_kho ADD COLUMN don_vi_id integer REFERENCES don_vi(id) ON DELETE SET NULL, ADD COLUMN bo_phan_id integer REFERENCES bo_phan(id) ON DELETE SET NULL`,
    );
    await queryRunner.query(
      `UPDATE phieu_nhap_kho receipt SET don_vi_id = organization.id FROM don_vi organization WHERE organization.ten = trim(receipt.don_vi)`,
    );
    await queryRunner.query(
      `UPDATE phieu_nhap_kho receipt SET bo_phan_id = department.id FROM bo_phan department WHERE department.don_vi_id = receipt.don_vi_id AND department.ten = trim(receipt.bo_phan)`,
    );
    await queryRunner.query(
      `CREATE INDEX idx_phieu_nhap_don_vi ON phieu_nhap_kho(don_vi_id)`,
    );
    await queryRunner.query(
      `CREATE INDEX idx_phieu_nhap_bo_phan ON phieu_nhap_kho(bo_phan_id)`,
    );
  }
  async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(
      `ALTER TABLE phieu_nhap_kho DROP COLUMN bo_phan_id, DROP COLUMN don_vi_id`,
    );
    await queryRunner.query(`DROP TABLE bo_phan`);
    await queryRunner.query(`DROP TABLE don_vi`);
  }
}
